goalsDictionary["BoIv1_1_1"] = {

easyGoals: [
        "Open 1 Potion Shop|1potion",
        "Have 8 Hearts|8hearts",
        "Din's Fire|dinsFire",
        "Shield Technique|shieldTechnique",
        "Big Bomb Bag|bombBag",
        "Activate 10 Sheikah Stones|10stones",
        "Defeat Freddie|freddie",
        "Snorkel|snorkel",
        "Touch the Bench|bench",
        "Gerudo Village Puzzle|gerudoPuzzle",
        "Windmill Puzzle|windmillPuzzle",
        "Tingle Puzzle|tinglePuzzle",
        "Hold 5 Dekuseeds|5seeds",
        "3 Gears|3gears",
        "Wake the Zora Prince|zoraPrince",
        //"Get Ring of Blasting from the mountain fountain|mountainFountain",  //apparently not guaranteed to spawn
        //"Get Ring of Risk from the swamp fountain|swampFountain",
        "Kill Keymos|keymos",
    ],

mediumGoals: 
    [
        "Big Quiver|quiver",
        "Gerudo Mines F1 Miniboss|mines1",
        "Gerudo Mines F2 Miniboss|mines2",
        "Frozen Grotto F1 Miniboss|grotto1",
        "Frozen Grotto F2 Miniboss|grotto2",
        "Lost Swamp F1 Miniboss|swamp1",
        "Lost Swamp F2 Miniboss|swamp2",
        "Temple of Storms F1 Miniboss|storms1",
        "Temple of Storms F2 Miniboss|storms2",
        "3 Overworld Mapping Items|3mapItems|Three of Cave / Treasure / Skull / Warp Charm and Telescope",
        "4 Overworld Mapping Items|4mapItems|Four of Cave / Treasure / Skull / Warp Charm and Telescope",
        "Open 2 Potion Shops|2potions",
        "Open 3 Potion Shops|3potions",
        "Have 10 Hearts|10hearts",
        "Activate 15 Sheikah Stones|15stones",
        "Goron Charm|goronCharm",
        "2 Bottles|2bottles",
        "3 Bottles|3bottles",
        "Explore the Four Corners|fourCorners",
        "Explore Every Beach Tile|exploreBeach",
        "Explore Every Desert Tile|exploreDesert",
        "Explore Every Swamp Tile|exploreSwamp",
        "Explore Every Mountain Tile|exploreMountains",
        "Open 2 Fairy Fountains|2fountains",
        "Get Stamina Increase|staminaUp",
        //"4 Gears|4gears",
        "4 Special Daggers / Shortswords|4daggers",
        // "I AM ERROR|iAmError",
        "Hold 250 Rupees|250rupees",
        "Hold 4 Keys|4keys",
        "Hold 10 Diamonds|10diamonds",
        "Hold 15 Diamonds|15diamonds",
        "Infuse Weapon|infuse",
        "Defeat 2 Dark Stairs Minibosses|2darkStairs",
        "Open 2 Puzzle Cave Purple Chests|2puzzleCaves|Puzzle caves are the ones with round entrances.  One always appears by Zelda's tower, and one always appears by Link's house.",
        "Unlock Link/Zelda|wakeLink",
        "Unlock Cadence|cadence",
        "Fairy in a Bottle|fairyBottle",
        "Bee in a Bottle|beeBottle",
        "Anti-Fairy in a Bottle|antifairyBottle",
        "Fish in a Bottle|fishBottle",
        "Clear the Hover Shrine|hoverShrine|You do not need to open the chest once you clear the screen.",
    ],

hardGoals: 
    [
        "Defeat Wizroboe|oboe",
        "Defeat Wizroboe as Link|oboeLink",
        "Defeat Wizroboe as Cadence|oboeCadence",
        "Defeat Wizroboe without using explosives|oboeNoBombs|Bombs, Bombchus, Din's Fire, and Bomb Fairies are all banned.",
        "Defeat Gleeokenspiel|glockenspiel",
        "Defeat Gleeokenspiel as Link|glockenspielLink",
        "Defeat Gleeokenspiel as Cadence|glockenspielCadence",
        "Defeat Gleeokenspiel without using explosives|glockenspielNoBombs|Bombs, Bombchus, Din's Fire, and Bomb Fairies are all banned.",
        "Defeat Gleeokenspiel after killing every Gleeokenspiel Head|glockenspielAllHeads",
        "Defeat Bass Guitarmos Knights|bass",
        "Defeat Bass Guitarmos Knights as Link|bassLink",
        "Defeat Bass Guitarmos Knights as Cadence|bassCadence",
        "Defeat Bass Guitarmos Knights using base dagger / shortsword|bassBase|Items and skills are allowed.",
        "Defeat Gohmaracas|maracas",
        "Defeat Gohmaracas as Link|maracasLink",
        "Defeat Gohmaracas as Cadence|maracasCadence",
        "Defeat Gohmaracas using base dagger / shortsword|maracasBase|Items and skills are allowed.",
        "Defeat Gohmaracas after breaking every bush in the arena|maracasAllBushes",
        "Defeat Dark Freddie|darkFreddie",
        "5 Overworld Mapping Items|5mapItems|All of Cave / Treasure / Skull / Warp Charm and Telescope",
        "Activate 25 Sheikah Stones|25stones",
        "Full Map Seen|allSeen|You do not have to visit every tile, but the entire map must be visible.",
        "Eli's Greatshovel|eliShovel",
        "Hold 8 Keys|8keys",
        "Hold 1000 Rupees|1000rupees",
        "Royal Rapier|royalRapier",
        "Caladbolg|caladbolg",
    ],

challengeGoals: 
    [
        "Start as Link|linkStart|You can go to Zelda's room for a map peek, but you must still start as Link.",
        "Don't get the Power Glove|noGlove",
        "Don't infuse any weapons|noInfuse|The special daggers / shortswords can still be used.",
        "Don't visit any Cadence caves|noCadenceCaves|You can still get the lute from I AM ERROR or in the castle infusion room. You can enter the caves, but if you pick up the key item, you lose this square.",
        "Don't open any purple dungeon chests|noDungeonChests",
        "Don't use any bombs|noBombs|You can pick up bombs, but you cannot use them.  Bombchus and Din's Fire are allowed.",
        "Don't spend any diamonds|noDiamonds|The diamond coupon can still be used.",
        "Don't spend any rupees|noRupees|You can still steal and use coupons. If your rupee count ever decreases you lose this square.",
        "Don't kill any shopkeepers|saveFreddie",
        "Don't pick up any heart containers|noHeartContainers|Heart pieces are allowed.",
        "Don't get the Zora's Flippers|noFlippers",
        "Skip Nayru's Love in Hyrule Castle|skipNayru|You can still pick up the shield (which includes Nayru's Love) at Link's house.",
        "No Major Dungeon Skips|noMajorSkips|1F skips and boss key skips are banned. For each dungeon floor, you must enter through the entrance, kill the miniboss, and exit through the exit.  Gear skip is also banned.",
    ],


finalGoals: 
    [
        "Defeat Octavo|octavo",
        "Defeat Ganon|ganon",
        "Fully Explore the Map|allExplored",
        "Unlock Yves|yves",
        "All Four Future Hyrule Legendary Weapons|legendaryWeapons|Hylian Flail, Fragarach, Impa's Nagintana, and Jeweled Dagger / Kokiri Sword are required.  The other legendary weapons are not required.",
        "All Three Character-Specific Legendary Weapons|characterWeapons|Royal Rapier, Caladbolg, and Eli's Greatshovel are all required.  The other legendary weapons are not required.",
        "All Permanent Usable Items|allItems|All permenent items and their respective upgrades, including L/R skills. Passive items and capacity upgrades are not required.",
        "One Permanent Weapon of Each Type|allWeapons|Glass weapons do not count, but legendary weapons do.  You must have a shortsword, dagger, broadsword, spear, flail, longsword, rapier, and greatshovel."
    ],

exclusions: 
    [
        ["noCadenceCaves","dinsFire"],
        ["noCadenceCaves","shieldTechnique"],
        ["noInfuse","infuse"],
        ["saveFreddie","freddie"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","grotto2"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","mines2"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","storms2"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","swamp2"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","oboe"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","glockenspiel"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","maracas"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","bass"],
        ["octavo","ganon","legendaryWeapons","characterWeapons","wakeLink"],
        ["characterWeapons","caladbolg"],
        ["characterWeapons","royalRapier"],
        ["yves","5seeds"],
        ["yves","staminaUp"],
        ["yves","tinglePuzzle"],
        ["allExplored","fourCorners"],
        ["allExplored","allSeen"],
        ["noCadenceCaves","bassCadence"],
        ["noCadenceCaves","glockenspielCadence"],
        ["noCadenceCaves","oboeCadence"],
        ["noCadenceCaves","maracasCadence"],
        ["3bottles","noDiamonds"],
        ["yves","allExplored","caladbolg"],
        ["yves","allExplored","royalRapier"],
        ["yves","allExplored","darkFreddie"],
        ["yves","allExplored","octavo","characterWeapons","eliShovel"],
        ["glockenspiel","glockenspielAllHeads","glockenspielLink","glockenspielCadence","glockenspielNoBombs"],
        ["oboe","oboeLink","oboeCadence","oboeNoBombs"],
        ["maracas","maracasLink","maracasCadence","maracasAllBushes","maracasBase"],
        ["bass","bassLink","bassCadence","bassBase"],
        ["allExplored","exploreBeach"],
        ["allExplored","exploreDesert"],
        ["allExplored","exploreSwamp"],
        ["allExplored","exploreMountains"],
        ["allItems","noDungeonChests"]
    ]
};
