easyGoals = [
"Open 1 Potion Shop|1potion",
"Have 8 Hearts|8hearts",
"Din's Fire|dinsFire",
"Shield Technique|shieldTechnique",
"Big Bomb Bag|bombBag",
"Big Quiver|quiver",
"Activate 5 Sheikah Stones|5stones",
"Defeat Freddy|freddy",
"Snorkel|snorkel",
"Touch the Bench|bench",
"Gerudo Village Puzzle|gerudoPuzzle",
"Windmill Puzzle|windmillPuzzle",
"Tingle Puzzle|tinglePuzzle",
"Hold 5 Dekuseeds|5seeds",
"3 Gears|3gears",
"Wake the Zora Prince|zoraPrince",
"Get Scroll of Enchant Weapon from the beach fountain|beachFountain",
"Get Ring of Blasting from the mountain fountain|mountainFountain",
"Get Ring of Risk from the swamp fountain|swampFountain",
"Get Scroll of Need from the beach mimic|beachMimic",
"Kill the keymos|keymos"
]

mediumGoals = [
"Gerudo Mines F1 Miniboss|mines1",
"Gerudo Mines F2 Miniboss|mines2",
"Frozen Grotto F1 Miniboss|grotto1",
"Frozen Grotto F2 Miniboss|grotto2",
"Lost Swamp F1 Miniboss|swamp1",
"Lost Swamp F2 Miniboss|swamp2",
"Temple of Storms F1 Miniboss|storms1",
"Temple of Storms F2 Miniboss|storms2",
"3 Mapping Items|3mapItems",
"4 Mapping Items|4mapItems",
"Open 2 Potion Shops|2potions",
"Open 3 Potion Shops|3potions",
"Have 10 Hearts|10hearts",
"Activate 10 Sheikah Stones|10stones",
"Goron Charm|goronCharm",
"2 Bottles|2bottles",
"3 Bottles|3bottles",
"Explore the Four Corners|fourCorners",
"Open 2 Fairy Fountains|2fountains",
"Get Stamina Increase|staminaUp",
"4 Gears|4gears",
"Royal Rapier|royalRapier",
"Caladbolg|caladbolg",
"4 Special Daggers/Shortswords|4daggers",
"I AM ERROR|iAmError",
"Hold 250 Rupees|250rupees",
"Hold 4 Keys|4keys",
"Hold 10 Diamonds|10diamonds",
"Hold 15 Diamonds|15diamonds",
"Infuse Weapon|infuse",
"Timed Blue Chest|timedBlue",
"Flawless Purple Chest|flawlessPurple",
"Defeat 2 Dark Stairs Minibosses|2darkStairs",
"Defeat 3 Dark Stairs Minibosses|3darkStairs",
"Open 2 Puzzle Cave Purple Chests|2puzzleCaves",
"Open 3 Puzzle Cave Purple Chests|3puzzleCaves",
"Unlock Link/Zelda|wakeLink",
"Unlock Cadence|cadence",
"Fairy in a Bottle|fairyBottle",
"Bee in a Bottle|beeBottle",
"Anti-Fairy in a Bottle|antifairyBottle",
"Fish in a Bottle|fishBottle",
]

hardGoals = [
"Oboe|oboe",
"Glockenspiel|glockenspiel",
"Bass Guitar|bass",
"Maracas|maracas",
"Defeat Octavo|octavo",
"Defeat Ganon|ganon",
"Defeat Dark Freddy|darkFreddy",
"5 Mapping Items|5mapItems",
"Activate 15 Sheikah Stones|15stones",
"Full Map Seen|allSeen",
"Full Map Explored|allExplored",
"Unlock Yves|yves",
"Eli's Greatshovel|eliShovel",
"Hold 8 Keys|8keys",
]

challengeGoals = [
"Start as Link|linkStart|You can go to Zelda's room for a map peek, but you must still start as Link.",
"Don't get the power glove|noGlove",
"Don't infuse any weapons|noInfuse|The special daggers/shortswords can still be used.",
"Don't visit any Cadence caves|noCadenceCaves|You can still get the lute from I AM ERROR or in the castle infusion room.",
"Don't open any purple dungeon chests|noDungeonChests",
"Don't use any bombs|noBombs|You can pick up bombs, but you cannot use them.  Bombchus and Din's Fire are allowed.",
"Don't spend any diamonds|noDiamonds|The diamond coupon can still be used.",
"Don't kill any shopkeepers|saveFreddie",
"Don't pick up any heart containers|noHeartContainers|Heart peices are allowed.",
"Don't get the Zora's flippers|noFlippers",
]


var exclusions = [
];
